### ISSUE TITLE
FASTA import fails, regex wanted

### ISSUE THREAD

**Issue by dblyon** [compomics/searchgui#115]
Dear Compomics team,

I want to import a custom made fasta (containing SwissProt and other entries from specialized DBs) into SearchGUI for metaproteomics analysis. The headers are in a consistent format, but NOT in the UniProt format.
Here's the format schmema:
">DataBase|AccessionNumber|Description OS=TaxNamePreferred NCBI_TaxID=TaxID"
e.g.
">vir|PRO_0000390875| OS=Murine leukemia-related retroviruses NCBI_TaxID=99182"
or e.g.
">sp|P31946|1433B_HUMAN 14-3-3 protein beta/alpha GN=YWHAB PE=1 SV=3 Homo sapiens OS=Human NCBI_TaxID=9606"

It would be great if I could just define a regular expression like:
"^>(\w+)\|(.*?)\|.*?OS=(.*?)\s(?:\w+=.+?\s)*NCBI_TaxID=(\d+)"
to parse the fasta header.

How can I get this fasta imported/to work with SearchGUI???

Thank you for your efforts and support!!
Best regards,
David

**Comment by mvaudel** [comment]
Dear David,

Unfortunately not all search engines support custom headers so we cannot implement a regular expression like one would do with MaxQuant or Mascot. Would it be possible for you to convert your headers to another format? At the link below you will find the details of a header that we tested on all algorithms implemented in SearchGUI. It should make it possible for you to search your data :)

http://compomics.github.io/searchgui/wiki/databasehelp#non-standard-fasta

Hope this helps, don't hesitate to write again if you encounter issues with the database formatting.

Marc

**Comment by dblyon** [comment]
Thank you for the quick reply!! I've modified the headers accordingly. The import now works.
Best regards,
David

**Comment by mvaudel** [comment]
Great! Don't hesitate to write again if you encounter new issues. Where do the non-uniprot sequences come from if I may ask?

**Comment by dblyon** [comment]
They are from the Human Oral Microbiome (http://www.homd.org/). We're looking at Viking teeth :) (dental calculus preserves proteins relatively well). 
Thank you for your kind support!!

**Comment by dblyon** [comment]
I would indeed have two questions :)

1. There is a very slow step in the pipeline. I believe it is the indexing step of tryptic peptides to proteins from Crux. Is there any way to speed up this step? It's been running for almost a day, for a fasta of 1.3GB size and it's is only using around 10-30% CPU, running on a SSD.
Here's the Progress status:
INFO: Beginning tide-index.
INFO: Writing results to output directory 'crux-output'.
INFO: CPU: Ody.local
INFO: Crux version: 3.0.17109
INFO: Mon Aug 29 15:20:09 CEST 2016
INFO: Running tide-index...
INFO: Writing results to output directory 'fasta-index'.
INFO: Reading ..._searchGUI_concatenated_target_decoy.fasta and computing unmodified peptides...
INFO: Ignoring 79025 peptide sequences containing unrecognized characters
INFO: Reading proteins

2. Do you have any suggestions for the "peptide sequences containing unrecognized characters"? I think this comes from the asterisks ( "*") for stop codons.

**Comment by hbarsnes** [comment]
Hi David,

For issues with the search engines themselves I would recommend that you contact the search engine developers directly, as there is not much we can do unless the problem is our input to the search engine. 

For Tide there is a Google Group where you can ask questions: https://groups.google.com/forum/#!forum/crux-users. Hopefully they will be able to help you.

Also, if you don't specifically have to run Tide you could leave it out and run SearchGUI with the other search engines instead. Comet and Tide are basically the same algorithm anyway (both based on Sequest), so if you include Comet you should get more or less the same results as with Tide.

Regarding unrecognized characters I would generally recommend removing stars from the sequences as it is unclear how these are to be interpreted, but the unrecognized characters could also be X or similar. Not sure how to figure out which characters that are not recognized by the different search engines. This would again be a question for the search engine developers. :)

Best regards.
Harald

**Comment by dblyon** [comment]
Hey Harald,

Thank you for the quick reply!! I'll contact the appropriate people then. 

Best regards,
David
