### ISSUE TITLE
convert corrupt thermo raw file

### ISSUE THREAD

**Issue by dblyon** [compomics/searchgui#119]
Dear Compomics-team and users,

I know this is an independent issue from SearchGUI. Please excuse me for using this platform to ask for help! I'm hoping to reach somebody who has found a solution to my problem. Please let me know if there is any other platform I can post this issue on (I've already written to the Proteowizard team).

I would like to **convert a thermo raw file which is unfortunately corrupt**. Due to a power surge the computer shut down, but the LC and the MS didn't. So what I've got is **a 320 mb file that Xcalibur/MS files reader can't open**. Unfortunately, this is the most important sample I've ever dealt with since it is an unrecoverable and unique ancient sample.
I've tried to **convert from Thermo RAW to mzML** using the GUI and the CLI of msconvert, but I get the same error message "unable to open file". Is there ANY way I can read and convert some of this data? 
Maybe there is some kind of end tag these raw files have that I can add to the corrupted file to make it legible? I'm thinking in terms of 
Please let me know if you have any suggestions or tipps! 
Thank you very much for your time and support!

Best regards,
David

**Comment by mvaudel** [comment]
Hi David,

Sorry to hear that things broke down on such an important sample. I am afraid we don't work with the raw data directly and always use Proteowizard. Did you ask Thermo about it? Maybe someone else had the issue before or they encountered it internally?

In the academic community, the Proteowizard team has outstanding expertise so I think they will be able to help better than us! Otherwise, I would recommend contacting David Bouyssié at the IPBS in France - he is one of the few that has looked at the raw data in their binary format (1s and 0s).

You might be able to reach other bioinformaticians through the (new) proteomics Q&A. Maybe one of them will have done this already?
qa.proteomics-academy.org

I am not sure how much can be rescued from the file. The only thing I am quite confident with is that it will not be easy!

Hope this helps,

Marc

**Comment by dblyon** [comment]
Dear Marc,

thank you very much for the tipps of who to contact and your kind words!! I'll try it there and will report back here in case I encounter any solution.

Best regards,
David
