### ISSUE TITLE
Converting mgf to apl Andromeda compatible files

### ISSUE THREAD

**Issue by kapilaGIT** [compomics/searchgui#124]
My question is:

How do you convert mgf files to andromeda. I would like to do the same for maxquant, but I always get the file corrupted error, when I submit mzXML file converted from mgf using msconvert. 

Best regards

Kapila

**Comment by mvaudel** [comment]
Hi Kapila,

Andromeda takes apl files as input, which is very similar to mgf. I am not sure whether this is supported in msconvert, though.

I am also not sure what you mean by _I would like to do the same for maxquant_. MaxQuant needs the ms1 spectra as well as instrument specific information and these are not included in mgf files, so mzXML from mgf is certainly not going to work. In general it is better to use the raw files in MaxQuant.

Hope this helps,

Marc

**Comment by kapilaGIT** [comment]
Hi Marc,

Thank you very much for the quick reply. Ok so that means I could not submit the reduced files like mgf to MaxQuant since some information like ms1 is missing in the mgf files. 

I have a another question some times searchgui complains that the search result files of some of the search engines could not find immediately after the search is completed. I just tried to look at the log files or the search engine specific folders, but I could not find any. Is there a way track down these type of errors. Since I provide the output path is it the place where all these temporary files are written?

Best regards and thank you again for your quick reply.

Kapila

**Comment by mvaudel** [comment]
Hi again,

In general, when this error occurs it is because the search engine did not complete its search and did not produce any result file. Intermediate results are located in a folder called _searchgui_temp_ in the temp folder you provided or the output folder if none provided. 

You will find the log of the different searches from the different search engines in the log file and in the html report created along with your search result. If you are operating from the GUI, the log can be found via the _Help -> Bug Report_ menu. If you are operating in command line the log will be in the resources folder of SearchGUI, unless you used the _log_ option to redirect the log. 

If you are using the command line, please remember to use a single instance of SearchGUI at a time because search engines use internal files we have no control upon. When using multiple SearchGUI in parallel it is recommended to make clean copies of the software for each run and use different temp folders. This can be the reason for a search not finishing properly as the different instances conflict with each others. You will find more information on the command line operation in the CLI wiki (see last paragraph of the introduction): https://github.com/compomics/searchgui/wiki/SearchCLI#searchgui-command-line-interface

Hope this helps,

Marc

**Comment by kapilaGIT** [comment]
Hi Marc,

Thank you for the detail response. The next question is on the same line as the original question. How do you convert mgf to apl.

Best regards

Kapila

**Comment by mvaudel** [comment]
Hi Kapila,

I am not aware of any converter and the formats are not that different so we do it directly in SearchGUI using [compomics utilities](https://www.ncbi.nlm.nih.gov/pubmed/21385435).
https://github.com/compomics/compomics-utilities/blob/master/src/main/java/com/compomics/util/experiment/io/massspectrometry/export/AplExporter.java

Best regards,

Marc

**Comment by kapilaGIT** [comment]
Hi Marc,

Thank you very much and appreciate all your help.

Best regards

Kapila

**Comment by mvaudel** [comment]
My pleasure! If you agree I will close the issue and should you encounter any problem related to this feel free to write again and I will reopen it.

Best regards,

Marc
