### ISSUE TITLE
3.2.2 crashing on unspecific enzyme option

### ISSUE THREAD

**Issue by akwalker** [compomics/searchgui#132]
We use GluC+trypsin for searching and even with Promega Trypsin Gold, we have been having many non-specific cleavages. So instead of Trypsin+GluC (which I don't even see in the new release), I have to use the nonspecific option for the enzyme. In this new version, it crashes just after reading the mgf file and the search parameters. The error window says "Error: null" right after "extracting search settings". 

I repeated with the same settings and mgf but with trypsin selected and the search proceeded without an error. I switched back to unspecific and it immediately crashed. The bug report window gives this message:

Wed Dec 07 14:07:52 EST 2016: SearchGUI version 3.2.2.
java.lang.NullPointerException
	at eu.isas.searchgui.processbuilders.TandemProcessBuilder.<init>(TandemProcessBuilder.java:276)
	at eu.isas.searchgui.SearchHandler$SearchWorker.doInBackground(SearchHandler.java:1982)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

I don't see any other log files generated.

Thanks,
Angela

**Comment by hbarsnes** [comment]
Hi Angela,

Thanks for telling us about this. I can confirm that we see the same issue with the unspecific enzyme on our side as well. We will correct it and release a new version shortly.

Regarding the removal of Trypsin+GluC, this is due to a required simplification of our enzyme settings. We are however looking into making it possible for users to create their own enzymes (see https://github.com/compomics/searchgui/issues/130). This should also be ready soon. We'll keep you posted and let you know as soon as this is possible.

Best regards,
Harald

**Comment by hbarsnes** [comment]
Hi Angela,

New versions of both SearchGUI and Peptideshaker have just been released which should fix the problems with using the unspecific enzymes option. If this is not the case, please let us know and we'll reopen the issue.

For future progress on supporting user defined enzymes please refer to #130.

Best regards,
Harald
