### ISSUE TITLE
Errors with Andromeda searches and results file isn't written to .zip

### ISSUE THREAD

**Issue by akwalker** [compomics/searchgui#136]
When I search with Andromeda, it writes the final zip file but says it can't write the results file. 

![sg error](https://cloud.githubusercontent.com/assets/23129024/21941569/5bebbf9a-d997-11e6-8287-d34851d9d042.jpg)

In addition, I get a pop up error window in the middle of the search. T
his is what is shown in the window when it finishes:

# ------------------------------------------------------------------
# SearchGUI 3.2.5 Report File
#
# Originally saved by: akwalker @ Beastie
#                  on: 13 Jan 2017, 13:44
#                  as: SG ANDROMEDA ERROR
# ------------------------------------------------------------------

Fri Jan 13 12:55:46 EST 2017        Andromeda configuration.

Fri Jan 13 12:55:46 EST 2017        Indexing spectrum files.
Fri Jan 13 12:55:47 EST 2017        Extracting search settings.

Fri Jan 13 12:55:47 EST 2017        Converting spectrum file UM_F_50cm_2017_0740_CID35.mgf for Andromeda.
Fri Jan 13 12:55:54 EST 2017        Processing UM_F_50cm_2017_0740_CID35.mgf with Andromeda.

Start Search.

Unhandled Exception: System.Exception: Exception during execution of external process: 3328
   at BaseLibS.Util.WorkDispatcher.ProcessSingleRunExternal(Int32 taskIndex, Int32 threadIndex)
   at BaseLibS.Util.WorkDispatcher.DoWork(Int32 taskIndex, Int32 threadIndex)
   at BaseLibS.Util.WorkDispatcher.Work(Object threadIndex)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

Fri Jan 13 12:57:13 EST 2017        Andromeda finished for UM_F_50cm_2017_0740_CID35.apl (1 minute 19.0 seconds).

Fri Jan 13 12:57:13 EST 2017        Could not find Andromeda .res file for UM_F_50cm_2017_0740_CID35.mgf.
Fri Jan 13 12:57:13 EST 2017        Zipping output files.

Fri Jan 13 12:57:13 EST 2017        Search Completed (1 minute 26.0 seconds).

**************************************************************************************************

I don't think I've ever had an Andromeda search complete successfully but I know others use it so I'm guessing it parameters or something I'm doing different. 

Angela

**Comment by hbarsnes** [comment]
Hi Angela,

Thanks for telling us about this. I'm afraid the Andromeda error message makes as little sense to be as it does to you though. But I would suspect that it is somehow related to your search setting not being handled correctly, either on our side in the way we provide them to Andromeda or due to an issue inside Andromeda itself.

Would it be possible for you to make the data available to us (mgf, FASTA and search settings) so that we can try to reproduce the error on our side?

Best regards,
Harald

**Comment by hbarsnes** [comment]
Hi Angela,

As I didn't hear back from you I assume you managed to resolve the issue on your own? If not please let us know and we'll reopen the issue. And then it would be great if you could make the data available to us (mgf, FASTA and search settings) so that we can try to reproduce the error on our side?

Best regards,
Harald
