### ISSUE TITLE
Light and heavy label

### ISSUE THREAD

**Issue by norazrin** [compomics/searchgui#143]
Hi, 

Can you add these mods on the list?
-Dimethyl (light label)= Lys0, Nter0
Dimethyl (heave label)= Lys4, Nter4

Thank you very much.

**Comment by hbarsnes** [comment]
Hi,

Have you checked the dimethyl modifications that are already included? You'll see them if you choose "All Modifications" instead of "Most Used Modifications" in the drop down menu above the modification list in the search settings dialog. Or is there some reason why you cannot use these?

Also, you can always add you own custom modifications by clicking the cogwheel next to the above mentioned drop down menu and click Edit under the User Modifications table.

Best regards,
Harald

**Comment by hbarsnes** [comment]
Issue assumed resolved. If this is not the case, please let us know and we'll reopen the issue.
