### ISSUE TITLE
no DTT

### ISSUE THREAD

**Issue by chemllama** [compomics/searchgui#152]
I exposed human serum transferrin to homocysteine in hopes of being able to see homocysteinylation, but that meant when I ran it on the mass spec (QTOF) I did not use DTT. Is there any way to take this into account in the spectrum matching process?

**Comment by mvaudel** [comment]
Hi,

If you mean that you did not reduce and alkylate your cysteines then you can just remove the carbamidomethylation of Cysteines from your search parameters. I am not totally sure about the workflow you are referring to. Since this is not a SearchGUI specific question I recommend posting your question with a bit more details on qa.proteomics-academy.org, there will be people able to help you better than me there :)

Best regards,

Marc

**Comment by chemllama** [comment]
Marc,

awesome, thanks-you for the suggestion.

-Steven

**Comment by mvaudel** [comment]
Great, I just saw your message, the additional information greatly help, I will take it there and close this issue. If you encounter further problems don't hesitate to open a new issue or comment below and I will reopen this one.

Best regards,

Marc
