### ISSUE TITLE
andromeda search returns no output

### ISSUE THREAD

**Issue by adder** [compomics/searchgui#155]
Hey 

When I try to run andromeda I get an empty output file.
There is no error in the log.
I tried several settings to narrow down the problem but I always get the same error. 
Other search engines like msgf+ do successfully run with these parameters.

This is a link with the searchgui output + fasta + mgf + log
https://drive.google.com/open?id=0B-wZVKF6tmF1WXpLWjVDV1NtWkU

Best regards
Adriaan

**Comment by hbarsnes** [comment]
Hi Adriaan,

The Andromeda search works fine on my side with your data if I change the enzyme specificity to "Specific". (In fact, I cannot set it to anything but "Specific" as there seems to be a bug in the GUI for the test for which search engines that support this feature. I will look into this and get back to you later. Just need to get the new utilities backend to be supported in SearchGUI first.)

As to Andromeda providing an empty results file, I'm afraid Andromeda is pretty bad at giving any information if the search fails. You could try contacting the [Andromeda developers](https://groups.google.com/forum/#!forum/andromeda-list)? If so, I'd recommend sending them the Andromeda command line directly (which you can find in the SearchGUI resources\conf folder and just ignore the fact that the command line was generated by SearchGUI. :)

Best regards,
Harald

**Comment by adder** [comment]
Hey Harald

Thanks for answering!!
With working fine, you mean that it does not produce an empty results file when you change specificity to specific? 
Actually in this experiment we want to know about the non specific cleaved peptides so I need the non specificity setting. :)
The search seems to work with maxquant so maybe there is something different with stand alone and the maxquant version of andromeda that leads to the bug?

Best regards
Adriaan

**Comment by hbarsnes** [comment]
Hi Adriaan,

> With working fine, you mean that it does not produce an empty results file when you change specificity to specific?

Yes, it produced a .res file that I could load in PeptideShaker.

> Actually in this experiment we want to know about the non specific cleaved peptides so I need the non specificity setting. :)

I thought as much. Running a new search now with the wanted specificity after a quick manual edit of the parameter file to bypass the GUI bug. Will let you know when/if it completes.

> The search seems to work with maxquant so maybe there is something different with stand alone and the maxquant version of andromeda that leads to the bug?

Maybe. It would not be the first thing that is slightly different between the two. Would be great if you could compare the two command lines used, and perhaps also the Andromeda parameter files (the .apar) files directly? Perhaps there is a small difference we don't know about.

Keep in mind that we have limited experience with these specific Andromeda settings. So thanks for testing. :)

Best regards,
Harald

**Comment by hbarsnes** [comment]
Hi again,

The search with "specificCTermOnly" worked fine as well. Took a long time to complete, but produced a non-empty .res file that I could load in PeptideShaker without any errors.

Here's the SearchGUI output and the zipped PeptideShaker project: 
- https://www.dropbox.com/s/1ktk3vy39qs24du/searchgui_out.zip?dl=0
- https://www.dropbox.com/s/qpd4ol94qi1lb29/PeptideShaker_output.zip?dl=0

Or are any of my settings different from yours..?

Best regards,
Harald

**Comment by adder** [comment]
Hey, 
Thanks a lot!
I'll try again and try, spot the differences and report back to you! :)

**Comment by adder** [comment]
Hey Harald,

So, I ended up using a different windows  computer and now I also gent non empty andromeda .res files. I really have no idea what happened on the first computer. I updated all dependencies and there was never an error showing up in the logs. 

However, when I look at the mzid export, I get a different number of identifications compared to the results you send me ( same mgf, fasta and par file) Only difference is I also run msgf along andromeda, but filtered these PSMs out for the comparison.
Not sure what happened here.

Best
Adriaan

**Comment by hbarsnes** [comment]
Hi Adriaan,

> when I look at the mzid export, I get a different number of identifications compared to the results you send me ( same mgf, fasta and par file) Only difference is I also run msgf along andromeda, but filtered these PSMs out for the comparison

How and when do you filter out the MSGF+ PSMs? Because if the results are kept as part of the PeptideShaker processing this may affect which PSMs (MSGF+ or Andromeda) that are picked as the best PSMs, i.e. the ones ending up in the mzid file. So in order to get a direct comparison you would have to load the Andromeda results separately in PeptideShaker.

Best regards,
Harald

**Comment by adder** [comment]
Hey, 
When I load only the andromeda data I still have somewhat different results. Your search returned 410 hits and mine only 9. These are my search results if you are interested, mgf and fasta are included:
https://drive.google.com/open?id=0B-wZVKF6tmF1SDNKQ21nWEVfWEE

Best regards
Adriaan

**Comment by hbarsnes** [comment]
Hi Adriaan,

I had a look at the two parameter files and the only thing that popped up where the custom Ace13C2D3 modifications. In my parameter file both of these have a mass of 47.03765288283, while in your parameter files I see both 47.03610459649 and 48.04392962856, due to different combinations of hydrogen isotopes in the formula.

So I would start there and make sure that modification mass is correct. Pretty sure the one in my parameter file is the correct one? At least I get lots of peptides with the two modifications while a loading of your SearchGUI output in PeptideShaker returns no peptides with these modifications (at least for the variable one, forgot to check the fixed one). How/why they would be different in the two parameter files I don't know though, as I used your parameter (only changing the path to the FASTA file)...

BTW, I see that you added a Unimod link to UNIMOD:35 for your custom modifications, which is obviously not the correct mapping for these modifications. I guess you did this because Unimod did not contain the given modifications? In that case it's very much recommended to keep the links empty, as the corresponding Unimod CV terms will be used when exporting to mzid if a link is provided. Which will of course completely mess up your mzid export if the link refers to the wrong modification. ;)

Best regards,
Harald

**Comment by adder** [comment]
Hi Harald,

Sorry for the delay in answering your questions!
Thanks for all the effort you put into this.
I looked at the parameter files and I know why you got hits in your search and I didn't.
In your parameter file you were searching for the mass 47.03765288283.
Which was an approximation for the real mass of the heavy acetyl modification  I was searching for (48.04392962856 - hydrogen = 47.03610459649)
But I guess there something going wrong in the translation of the searchgui setting to andromeda setting because the 48.04392962856 - hydrogen is not being searched for, hence the zero hits I found.

Anyways, when I search for the 47.03765288283 modification with both andromeda and msgf+, I still get a multitude more hits with msgf+. Maybe that's because of the search engine itself, but the difference is striking.

You are off course completely right about me setting  Unimod link to UNIMOD:35 being wrong. I did it because I thought i would not being able to export the results if this was blank (I got the impression from the help in searchgui) but I now realise I can indeed keep it blank.

Best regards and again many thanks
Adriaan

**Comment by hbarsnes** [comment]
Hi Adriaan,

I know it's been a very long time, but was there ever any progress on this issue?

If not, you can perhaps see if the issue still exists in the new beta releases of SearchGUI and PeptideShaker?

Please see https://groups.google.com/forum/#!topic/peptide-shaker/1ecY0IyMOBM for more details.

If the issue still exists in the beta releases, please open a new issue at https://github.com/compomics/peptide-shaker-2.0-issue-tracker/issues.

Best regards,
Harald

**Comment by hbarsnes** [comment]
Issue assumed resolved with the release of the new versions. If this is not the case, please let us know and we'll reopen the issue.
