### ISSUE TITLE
can't add decoys to target fasta

### ISSUE THREAD

**Issue by ollykiseleva** [compomics/searchgui#158]
Dear collegues,
Could you please guide me with adding decoys to my customized fasta? It seems to me that I'm doing something wrong :)
I'm planning to use costomized sequences and sequences of contaminating proteins (from cRAP). Unfortunately, during setup adjustment I can't add decoy sequences (decoy button is inactive and Decoy Tag is marked with RND).
My fasta, cRAP fasta and printscreen are here https://www.dropbox.com/sh/ktxqfke870xq1x3/AAC55qWAlCn6tnv8VrMMp86ea?dl=0
Thank you for your amazing work!

Sincerely,
Olga

**Comment by hbarsnes** [comment]
Hi Olga,

The problem is due to four of your custom protein headers having accession numbers that end with "RND" which our code assumes to indicate that these are reversed versions of the protein sequences. An easy fix is to do a search and replace for your FASTA file, replacing "RND|" with, for example, "RND_|" (the "_" can be replaced by any character, however white space is not recommended).

As a general tip, I would also recommend having a look at our suggestions for custom FASTA file headers, which overall reduces the chance of errors when using non-standard headers.

Best regards,
Harald

**Comment by ollykiseleva** [comment]
Hi Harald,

Thank you very VERY much! Your advice was absolutely helpful!
I tried to look through the suggestions, but the solution seems to have slipped from me somehow.

However, great thanks again!

Sincerely,
Olga
