### ISSUE TITLE
SearchGUI image can't locate files as inputs

### ISSUE THREAD

**Issue by davidserv** [compomics/searchgui#159]
Hi,

I get the following error message everytime I run the SearchGUI image:

"Database not found. Run -usage to see the list of supported options and their input."

Here is the command i type to run the image:

"sudo docker run quay.io/biocontainers/searchgui:3.2.20--py36_0 searchgui eu.isas.searchgui.cmd.IdentificationParametersCLI -out parameters -db uniprot-all_concatenated_target_decoy.fasta
"

Whenever I run SearchCLI and the peptideshaker images I get the exact same error message as the one above. The two images on the Quay Docker repository failed to locate files on my host computer. Because of that, I can't use them at all.

Please help me with this. 

David S.

**Comment by CarlosHorro** [comment]
Hello,

I think there is an error in that command. As you are specifying " -db uniprot-all_concatenated_target_decoy.fasta" , you should have that file into the docker container, which it isn't. 
In order to avoid this problem, you can map a local folder with the .fasta file to the docker container, like:

sudo docker run -v /localmedia/shared:/docker_shared_resources quay.io/biocontainers/searchgui:3.2.20--py36_0 searchgui eu.isas.searchgui.cmd.IdentificationParametersCLI -out parameters -db /docker_shared_resources/uniprot-all_concatenated_target_decoy.fasta

Now searchgui should be able to find the .fasta file.

Greetings,
Carlos

**Comment by davidserv** [comment]
Hi Carlos,

Thank you, I appreciate the answer. The reason why I closed the issue was because I figured this all out with someone's help. Now it is solved ! I am new enough with Docker to bump into small problems like this one.

Also I noticed that the compomics.github.io project pages could be updated so that:

1) instead of giving the command line to run the docker image from the mulled project ("docker run quay.io/mulled/searchgui:X.Y.Z--1 searchgui eu.isas.searchgui.cmd.FastaCLI") give the command to run it from the biocontainers project, the command I tried to make it work.

2) on top of that why not giving your solution to map the files on the host to the docker container.

David S.
________________________________

**Comment by hbarsnes** [comment]
Hi David,

Thanks for the suggestions to update the documentation. We'll look into it and try to make it better. To be honest, we're pretty new to Docker ourselves. So the documentation should improve as we get more familiar with it. :)

Best regards,
Harald

**Comment by davidserv** [comment]
Alright. Good job with the biocontainer though and thanks for the reply !

David S.
________________________________
