### ISSUE TITLE
Bug: can't run DirecTag via commandline

### ISSUE THREAD

**Issue by tivdnbos** [compomics/searchgui#162]
Hi,

When I try to run DirecTag via the commandline, it throws the error that it cannot find the folder where DirecTag is placed in. Reason for this is that the folder (../resources/DirecTag/linux) is subdivided in two other folders, a 32-bit and 64-bit folder. When I copy the files from the linux_64bit folder into its parent folder, it works.

Best, 
Tim

**Comment by hbarsnes** [comment]
Hi Tim,

Strange. I don't see any errors in the code that could explain this. Which operating system are you using?

And I assume you are not using the -directag_folder option as part of your command line?

Best regards,
Harald

**Comment by hbarsnes** [comment]
Hi again,

Found the problem! There is a minor bug in the graphical user interface (GUI) version of SearchGUI where it is assumed that DirecTag does not have individual 32 and 64 bit versions. This means that if the GUI version is run it will set the DirecTag folder to the parent linux folder. This can however easily be corrected in the GUI via the Edit > Software Locations menu option.

The command line uses the default search engine folders if these are set (which they will be if the GUI has been run). However, if you run the command line without having run the GUI on the given machine before it will not be affected by the above bug and the correct default search engine folders will be used. (Which probably explains why we had not detected this issue before.)

We will fix this error in the next SearchGUI release. In the mean time you can fix the problem by correcting the path in the GUI as explained above.

Thanks for telling us about this bug so that we could fix it!

Best regards,
Harald

**Comment by hbarsnes** [comment]
Hi Tim,

We've just released SearchGUI v3.2.24 (and PeptideShaker v1.16.20) which should solve this issue. If this is not the case, please let us know and we'll reopen the issue.

Best regards,
Harald
