### ISSUE TITLE
Double Digest and customizable enzymes

### ISSUE THREAD

**Issue by hazbeck** [compomics/searchgui#165]
Gentlemen,
Could you please help me with the simple issue of double and triple digest.
When I am using GPM X!Tandem standalone version I can define my cleavage sites any way I want.
Same goes with Mascot and to lesser extend with Proteome Discoverer.
It appears to me that SearchGUI has quite limited number of preloaded available proteases and till now
I could not find a way to either edit them or add new ones.  Your help will be appreciated.
Cheers

**Comment by hazbeck** [comment]
Looks like this particular issue was already addressed and 3.1.4 release gives an opportunity to define custom digestion patterns. Next question arises which particular version of Peptide Shaker is compatible with 3.1.4 release. I tried latest Peptide Shaker and it did not work at all, while one of the earlier 2015 year releases was working quite fine. May be there is an updated version which was specifically designed for 3.1.4 ? Cheers

**Comment by mvaudel** [comment]
Hi and thank you for contacting us on this,

1- On the use of multiple enzymes: Currently multiple enzyme digestion is only available via the command line interface. The reason for this is that most people using multiple enzymes use Lys-C combined with trypsin, which does not require any additional setting since the cleavage of Lys-C is captured by trypsin. As far as I can remember, you are the first user in ten years asking for it, that is why adding this feature in the user interface was not prioritized :) May I ask which enzymes you are combining?

2- On the edition of enzymes: this feature is not released but on our list as well. The reason for this is that we received only one request in ten years (LysArginase) so it was faster to add the enzyme manually than creating an interface for generic edition :) Here again we will be happy to extend our tool to best support this. What proteases do you have in mind that are not in our list?

3- On the version: we recommend using the latest version of both tools, these should support multiple enzymes but in command line only. We are in the process of releasing new versions and we gladly accept feature requests, so if the current setup is not covering your needs we will extend the tools accordingly.

Hope this helps,

Marc

**Comment by hazbeck** [comment]
Thanks for getting back.
If I am not mistaken this particular issue of customizable digestion patterns was already raised a couple of years ago. So I am definitely not the first one raising this point and to the best of my knowledge there are a plenty of applications requiring multiple digest, which is much more diverse than already discussed TrLysC. For example TrLysC - AspN or GluC is one of the frequently used combos to characterize cross-linked peptides. Despite the fact that SearchGUI is not designed for that purpose one can get enough info on non-crosslinked peptide coverage to figure out cross-linked one. This is one of the simple examples. I am just surprised that this GUI enzyme customizable option available in 3.1.4 (which I already downloaded) was completely dropped out in later editions. Indeed one can go to command lines and such but simple fact remain that both Mascot , Sequest and GPM give me this option without any additional hustle. So I am really puzzled by this voluntarily downgrade of the SearchGUI capabilities.

**Comment by mvaudel** [comment]
Hi and thanks for coming back on this,

Sorry for overlooking the previous request on such enzyme customization. The reason why we removed the Enzyme edition is that we have changed our object model precisely to improve our handling of multiple enzymes and partial digest, but we never got the time to restore the functionality of enzyme edition and to enhance the GUI for multiple enzyme digests. We are in the process of finalizing a new version and will try to include these functionalities then.

We will keep you posted with our progress and send you a beta version as soon as available.

Best regards,

Marc

**Comment by brendmillerj** [comment]
I apologize if my question has been answered or if I'm overlooking the answer in the documentation, but I cannot find the syntax for calling multiple digestions via the command line (e.g., Trypsin + LysC). Could you kindly assist? Thank you in advance and for all the hard working going into SearchGUI!

**Comment by hbarsnes** [comment]
Issue assumed resolved with the release of the new version of SearchGUI where you can set up your own enzymes via Edit > Enzymes in the main SearchGUI dialog. If this is not the case, please let us know and we'll reopen the issue.
