### ISSUE TITLE
Issues with custom PTMs or mgf input files or search parameters?

### ISSUE THREAD

**Issue by 1Moe** [compomics/searchgui#176]
Hi Harald and Marc,

Ms Amanda, Mirymatch and Andromeda terminate my SearchGui searches early, unsure why. Tide works but gives odd results.

X!tandem, MS-GF, and Comet seem to work reasonably well.

I've attached the SearchGui log file and the mgf in question(from a Bruker Ultraflex MALDI TOF, I named it mgf_test.log but just rename file ending to .mgf).

Any help or insight would be much appreciated.
Cheers
Moe
[SearchGUI 3.3.1 log.txt](https://github.com/compomics/searchgui/files/2016642/SearchGUI.3.3.1.log.txt)
[mgf_test.log](https://github.com/compomics/searchgui/files/2016599/mgf_test.log)

**Comment by mvaudel** [comment]
Hi Moe,
Thanks for sharing, can you also attach the html report that was produced after the search?
If you want to keep these files private, do not hesitate to send it to my email address: marc.vaudel at uib.no.
Thanks,
Marc

**Comment by 1Moe** [comment]
Hi Marc,
thanks, I've sent through the HTML files to you!

**Comment by mvaudel** [comment]
Hi again,

Thanks, the search engines seems to be encountering several issues:
- MS Amanda: it is a problem with the custom modification. We need to do some more testing and will come back to you.
- Myrimatch: it seems to be a problem with the formatting of the headers in your database resulting in the tool finding the same accession for multiple proteins. If you want to avoid such issues we recommend using a generic header (compomics.github.io/projects/searchgui/wiki/databasehelp.html).
- Tide and ms-gf: it seems that your protein sequences contain a substantial number of ambiguous amino acids (B, Z, and X), plus selenocysteines. These are not supported by all search engines. I am afraid there is not much we can do about it. If your database has many ambiguous characters, you might want to try running DirecTag (with a tag length of 3) in combination with PeptideShaker, in our experience it can perform better than search engines in such cases.

But in the end, if X!Tandem, Comet, and ms-gf+ worked fine, maybe it is sufficient?

Hope this helps,

Marc

**Comment by hbarsnes** [comment]
Hi Moe,

About the MS Amanda issues, they seems to be due to a bug in the way MS Amanda maps to Unimod, as it tries to find "Delta:H(8)" while the name in the MS Amanda settings file is "Delta:H(8)C(6)O(1)(K)".

There may also be some issues with two of your modifications (http://www.unimod.org/modifications_view.php?editid1=1312 and http://www.unimod.org/modifications_view.php?editid1=1313) not being in the verified part of Unimod and thus not in the latest Unimod xml file: http://www.unimod.org/xml/unimod.xml. (Note that the Unimod file included with MS Amanda is also not the latest. You can update it manually though.)

In any case, I'd recommend contacting the MS Amanda developers directly: https://groups.google.com/forum/#!forum/msamanda.

Also, it seems like you are using Java 10? I'd recommend changing to the more stable Java 8 as some of the issue you are having ("WARNING: An illegal reflective access operation has occurred") seems to only occur on Java 10 (and maybe Java 9?). There could also be a newer version of Java 10 that you could try?

Best regards,
Harald

**Comment by 1Moe** [comment]
Hi Marc and Harald,

thanks for your detailed answers:
I'm now just using  X!Tandem, Comet, and ms-gf+, which works fine.
I've changed to Java version 8.

Thanks for your help!
Moe
