### ISSUE TITLE
Importing database with non-unique accession numbers

### ISSUE THREAD

**Issue by tivdnbos** [compomics/searchgui#186]
Hi, 

I was wondering if there was a possiblity to let SearchGUI deal with non-unique accession numbers? This can be, but not necessarily, due to working with translated genome sequences. The sequences itself are different, since the redundancy is a priori removed with DBToolkit.
For example:

```
>sp|AccessionNumber1|E_coli_transcript_1
seq1
>sp|AccessionNumber1|E_coli_transcript_2
seq2
```

Best regards, 
Tim

**Comment by hbarsnes** [comment]
Hi Tim,

I'm not sure what you mean by "let SearchGUI deal with non-unique accession numbers"? The accession numbers have to be unique for each protein sequence in the FASTA file. Otherwise there is no way of referring back to a specific sequence? In other words your example above would not be valid if AccessionNumber1 is used as the accession number.

I'd recommend reformatting your headers according to our database help pages: https://github.com/compomics/searchgui/wiki/DatabaseHelp#non-standard-fasta. This way you can control what is picked up as the accession number. Perhaps you can use AccessionNumber1|E_coli_transcript_1 as the accession number instead of just AccessionNumber1?

Best regards,
Harald

**Comment by tivdnbos** [comment]
Hi Harald,

I created generic fasta headers for dealing with this.

Thanks!
Tim
