### ISSUE TITLE
Should I use multiple files?

### ISSUE THREAD

**Issue by soerendip** [compomics/searchgui#205]
I have several mgf files with 11plex TMT data. Each file belongs to one run. Now, I can give searchgui all files at once. Though, it seems to throw the contents in one pot. Is it possible to decompose the data afterwards with PeptideShaker? Apparently, it is better to run file by file. Would you agree?

**Comment by hbarsnes** [comment]
It depends on the experimental setup. If you have multiple mgf files due to fractionation you can safely process these together in PeptideShaker. The results will then be merged into one project. But there is a separate Fractions tab that can be used as a rough guide to tell you in which fraction (i.e. mgf file) the peptides and proteins where detected.

However, if you do TMT multiplexing, i.e. combining more than one TMT experiment, you will have to process the mgf files from each experiment separately in PeptideShaker.

**Comment by soerendip** [comment]
Ok, thanks!
