### ISSUE TITLE
java.lang.IllegalArgumentException: Accession numbers cannot contain quotation marks: 'JNENNGHK_00049 4,4'-diaponeurosporenoate glycosyltransferase'!

### ISSUE THREAD

**Issue by soerendip** [compomics/searchgui#206]
It would be nice if SearchGUI could support quotation marks in fasta files. It is just inconvenient to run into such incompatibilities every now and then. These fasta files were annotated with PROKKA, as far as I know. Which seems to be a standard tool for annotation of prokaryotic genomes.

**Comment by hbarsnes** [comment]
The problem here is not really the quotation marks in the accession number, but rather that the accession number is not parsed correctly from the FASTA header. When SearchGUI cannot recognize the FASTA header it sometime has to default to use the whole header as the accession number, which in this case would also include the description part of the header. I recommend taking a look at our database help page and how to deal with non-standard FASTA headers: https://github.com/compomics/searchgui/wiki/DatabaseHelp#non-standard-fasta. With some basic search and replace you should easily be able to set up FASTA headers that SearchGUI will be happy with.

**Comment by hbarsnes** [comment]
Issue assumed resolved. If this is not the case, please let us know and we'll reopen the issue.
