### ISSUE TITLE
java.lang.NullPointerException Error

### ISSUE THREAD

**Issue by arminsl** [compomics/searchgui#215]
Hi everyone,
I was trying to run SearchCLI 3.3.15 on a Linux server, but I received java.lang.NullPointerException error at the beginning. 
The log is:

> Java version: 11.0.1.
> java.lang.NullPointerException
> 	at com.compomics.util.experiment.identification.protein_sequences.SequenceFactory.loadFastaFile(SequenceFactory.java:575)
> 	at com.compomics.util.experiment.identification.protein_sequences.SequenceFactory.loadFastaFile(SequenceFactory.java:558)
> 	at eu.isas.searchgui.cmd.SearchCLI.call(SearchCLI.java:247)
> 	at eu.isas.searchgui.cmd.SearchCLI.<init>(SearchCLI.java:102)
> 	at eu.isas.searchgui.cmd.SearchCLI.main(SearchCLI.java:378)
> 

I've tried the exact files and settings with SearchGUI 3.3.15 on windows, and there was no problem.
Trying different versions of Java didn't solve the problem.

**Comment by hbarsnes** [comment]
Hi,

The issue is related to not finding the FASTA file, or rather that the path to the FASTA file is not found in the search parameters. Please make sure that you are using complete paths when referring to files or folders when on Linux.

If this does not solve the problem, it would be great if you could share the complete command lines used, including the one used to set up the search parameters?

Best regards,
Harald

**Comment by arminsl** [comment]
Thanks for your immediate response.
There was a problem in my FASTA file name and path.

With sincere thanks,
Armin
