### ISSUE TITLE
Comet version and compatibility with PEFF searching

### ISSUE THREAD

**Issue by mwfoster** [compomics/searchgui#230]
Can you update SearchGUI to the latest version of Comet [2018.01 rev. 4 (2018.01.4), release date 2019/02/13]? Does SearchGUI support searching of PEFF databases, and if so, can the results be fully viewed in PeptideShaker?

**Comment by hbarsnes** [comment]
> Can you update SearchGUI to the latest version of Comet [2018.01 rev. 4 (2018.01.4), release date 2019/02/13]?

Yes, I this should not be a problem. I'll look into it and let you know. (The reason it is not already updated is that we for a long time have been working on a new beta release of both SearchGUI and PeptideShaker, which already includes the latest versions of all of the search engines. However, due to other issues we have not yet been able to release it properly.)

> Does SearchGUI support searching of PEFF databases, and if so, can the results be fully viewed in PeptideShaker?

SearchGUI does not support PEFF databases, mainly because Comet is the only search engine supporting the format and we prefer not to have search engine specific input formats. This may change in the future though.

As for supporting the opening of PEFF-style search results in PeptideShaker, this is something we are currently working on as part of adding support for MetaMorpheus (https://github.com/smith-chem-wisc/MetaMorpheus), but I cannot at this time tell you when this will become available.

**Comment by hbarsnes** [comment]
I just had another look at what is required to update the current SearchGUI release to the latest version of Comet, and it requires a bit more effort than I had initially thought (especially given that we have already made the update in the current beta version we are working on). 

So if you only wanted the Comet update because of the PEFF-support (which we do not yet support in SearchGUI anyway), there is perhaps not an urgent need for the update? If that is the case, I hope you can wait for the next major release of SearchGUI instead?

**Comment by mwfoster** [comment]
No worries. The searches work with TPP and it's really the visualization of results I am most interested in. I make contact Jimmy Eng to see what he his working on I'm that regard. Thanks, Matt



On Apr 4, 2020 12:26 PM, Harald Barsnes <notifications@github.com> wrote:

I just had another look at what is required to update the current SearchGUI release to the latest version of Comet, and it requires a bit more effort than I had initially thought (especially given that we have already made the update in the current beta version we are working on).

So if you only wanted the Comet update because of the PEFF-support (which we do not yet support in SearchGUI anyway), there is perhaps not an urgent need for the update? If that is the case, I hope you can wait for the next major release of SearchGUI instead?

**Comment by wenbostar** [comment]
Hi @mwfoster, you may be interested in trying [PDV](https://github.com/wenbostar/PDV) for visualizing Comet search result.

**Comment by mwfoster** [comment]
Thanks, I will try this. Matt

**Comment by mwfoster** [comment]
I was able to load the data into PDV viewer but it gave an "Table not instantiated" error.

**Comment by wenbostar** [comment]
@mwfoster , Could you open an issue at https://github.com/wenbostar/PDV and provide an example of input data for testing?

Bo

**Comment by hbarsnes** [comment]
The new version of SearchGUI has just been released which includes the most recent version of Comet. Please let us know if there are still remaining problems and we'll reopen the issue. Note that PEFF support is still not implemented in SearchGUI/PeptideShaker though.
