### ISSUE TITLE
 Loading spectrataxonomy_searchGUI.xml(4) : error 4: Syntax error parsing XML.

### ISSUE THREAD

**Issue by AnkeTraut** [compomics/searchgui#237]
Dear all,

I want to use SearchGUI for my metaproteomics dataset. Usually SearchGUI works quite well with my *.raw files but this time I recived an error message. First the *.raw files were converted to *.mfg files without any written problems. But then the following error message appeared:

X! TANDEM Vengeance (2015.12.15.2)

Loading spectrataxonomy_searchGUI.xml(4) : error 4: Syntax error parsing XML.

The taxonomy parameter file "taxonomy_searchGUI.xml" did not contain the value "all".
Check your settings and try again.

An error was detected while loading the input parameters.
Please follow the advice above or contact a GPM administrator to help you.

Wed Apr 22 13:48:08 CEST 2020        X!Tandem finished for E:\ATS\Antarktis\190602_VE1_PM4_ToK_TS_AD_St_1_3_19.mgf (47.0 milliseconds).

Wed Apr 22 13:48:08 CEST 2020        Could not rename X!Tandem result for 190602_VE1_PM4_ToK_TS_AD_St_1_3_19.mgf.
Wed Apr 22 13:48:08 CEST 2020        Could not find X!Tandem result file for 190602_VE1_PM4_ToK_TS_AD_St_1_3_19.mgf.
Wed Apr 22 13:48:08 CEST 2020        Processing 190602_VE1_PM4_ToK_TS_AD_St_1_3_20.mgf with X!Tandem.

Have you any idea what happened? What can I do?

Thank you very much for helping...
Anke

**Comment by hbarsnes** [comment]
Hi Anke,

This indicates that X! Tandem had problem parsing the taxonomy_searchGUI.xml file, which basically refers to the location of the FASTA file, and is generally due to an issue with the path to the FASTA file. Please make sure that neither the name of the FASTA file nor the path to it contains any special characters that can mess up the XML parsing. More than two white spaces in a row will also results in the same error.

If you cannot find the root of the problem, you can always share your taxonomy_searchGUI.xml file and I can have a look. You'll find it under SearchGUI-3.3.18\resources\XTandem\windows\windows_64bit.

Best regards,
Harald

**Comment by AnkeTraut** [comment]
Hi Harald,

thank you very much. The name of the faste file contained an "ü". Now I changed it and SearchGUI is running. Thank you very much
Best regards,
Anke
