### ISSUE TITLE
Import NCBInr FASTA error - Accession numbers cannot contain quotation marks

### ISSUE THREAD

**Issue by VirginieJJ** [compomics/searchgui#251]
Dear Compomics team,

I want to import NCBInr database into SearchGUI for metaproteomics analysis but there was an error importing the FASTA file.
The error was "Accession numbers cannot contain quotation marks".  

The header have this format:
    >AHG90838.1 Malate dehydrogenase [Gemmatirosa kalamazoonesis]
    >WP_031551166.1 tRNA (cytidine(34)-2'-O)-methyltransferase [Oribacterium sp. FC2011]

In some headers, I have quotation mark in the description part. It seems that the regular expression doesn't separate the accession and the description part. I read your web page on Non Standard FASTA. Should I modify my headers ? 

Thank you for your efforts and support!!
Best regards,
Virginie

**Comment by hbarsnes** [comment]
Hi Virginie,

The reason seems to be that NCBI changed their FASTA header format. I will look into whether we can make an update to support them directly.

In the meantime I'm afraid you will have to modify the headers to get rid of the quotation marks. You can either replace then with the Non Standard FASTA headers or you should be able to do a simpler search and replace for just the quotation marks.

The Non Standard FASTA headers should look something like this:

```
>generic|AHG90838.1|Malate dehydrogenase [Gemmatirosa kalamazoonesis]
>generic|WP_031551166.1|tRNA (cytidine(34)-2'-O)-methyltransferase [Oribacterium sp. FC2011]
```

Best regards,
Harald

**Comment by VirginieJJ** [comment]
Thanks for your reply, I will try the Non Standard FASTA but this multiply by two the necessary disk space for all databases. 
Best regards,
Virginie

**Comment by hbarsnes** [comment]
Hi Virginie,

> this multiply by two the necessary disk space for all databases

Yes, this is not optimal of course. It should however not be required in the next major release of SearchGUI and PeptideShaker as I've now added a rule to parse the new NCBI headers properly.

Best regards,
Harald

**Comment by VirginieJJ** [comment]
Thank you !! 
Best regards,
Virginie

**Comment by hbarsnes** [comment]
The new version of SearchGUI has just been released adding support for parsing the new NCBI headers. Please let us know if it does not work as wanted and we'll reopen the issue.
