### ISSUE TITLE
FastaCLI neither works nor speaks

### ISSUE THREAD

**Issue by iquasere** [compomics/searchgui#264]
Greetings!

I am using searchgui 3.3.9 through Bioconda, and trying to create decoy database with FastaCLI with the command
```
searchgui eu.isas.searchgui.cmd.FastaCLI -in path/to/database.fasta -decoy
```
This outputs
```
Reindexing: database.fasta.
```
without producing the concatenated file. Is it producing some log file silently?

**Comment by iquasere** [comment]
Following #212 I also removed plicas, but it still won't budge

**Comment by CarlosHorro** [comment]
Hi @iquasere ,

The command you executed produce a log into the Conda environment you are using in order to execute "searchgui". As an example, in Mac miniconda is installed into /opt/miniconda3, and my conda environment is called "searchgui339". So, my SearchGUI log is located by default at

/opt/miniconda3/envs/searchgui339/share/searchgui-3.3.9-1/resources

However, if you want to locate it easily, I recommend to use the option -log <log_folder_location>.
Check also that you have writing permissions in both the "log_folder_location" and the "path/to/" (as the resulting .fasta file will be written there).

Apart from this, I've properly executed that version of FastaCLI via Bioconda with a detailed output, so there may be a problem with any of the things I mentioned abouve, the input file or even some older configuration file the tool is finding when executing it. Checking the logs will give us more clues about this.

Greetings,
Carlos

**Comment by iquasere** [comment]
So the log file was created, and reported I have the same ID two times (6OJY). However, this is a pdb ID, which is the same for different subunits:
```
>pdb|6OJY|F Chain F, Twitching motility pilus retraction ATPase
>pdb|6OJY|E Chain E, Twitching motility pilus retraction ATPase
>pdb|6OJY|C Chain C, Twitching motility pilus retraction ATPase
>pdb|6OJY|B Chain B, Twitching motility pilus retraction ATPase
>pdb|6OJY|A Chain A, Twitching motility pilus retraction ATPase
```
Do I have to rename these sequences, or is there an option to ignore these repeats, since they contain different sequences? (although very similar ones)

**Comment by hbarsnes** [comment]
Basically, you have to reformat the above headers so that SearchGUI can know how to parse them and thus what to use as the accession number for each protein sequence. I assume that in the above examples SearchGUI will try to use 6OJY as the accession number, which of course does not work as it is not unique.

Please have a look at our help for non-standard FASTA headers: https://github.com/compomics/searchgui/wiki/DatabaseHelp#non-standard-fasta

Hopefully you can easily reformat your headers into this format and in the process ensure that the resulting accession numbers will be unique.

**Comment by iquasere** [comment]
Isn't there an option in SearchGUI so it takes all IDs as they come and doesn't try to perform the cross-checks it does?

**Comment by iquasere** [comment]
After trying to replace all ```|``` with ```_```, I thought SearchCLI would not try to parse the IDs, but still I get
```
java.lang.IllegalArgumentException: Non-standard Halobacterium (Max Planck) header passed. Expecting something like '>OExyz (OExyz) xxx xxx xxx', but was 'OEC88974.1_TIGR01210_family_radical_SAM_protein_[Methanobacterium_sp._A39]'!        at com.compomics.util.protein.Header.parseFromFASTA(Header.java:412)
        at com.compomics.util.experiment.identification.protein_sequences.SequenceFactory.createFastaIndex(SequenceFactory.java:805)
        at com.compomics.util.experiment.identification.protein_sequences.SequenceFactory.getFastaIndex(SequenceFactory.java:711)
        at com.compomics.util.experiment.identification.protein_sequences.SequenceFactory.getFastaIndex(SequenceFactory.java:641)
        at com.compomics.util.experiment.identification.protein_sequences.SequenceFactory.loadFastaFile(SequenceFactory.java:582)
        at eu.isas.searchgui.cmd.FastaCLI.call(FastaCLI.java:74)
        at eu.isas.searchgui.cmd.FastaCLI.<init>(FastaCLI.java:58)
        at eu.isas.searchgui.cmd.FastaCLI.main(FastaCLI.java:184)
```

**Comment by hbarsnes** [comment]
> Isn't there an option in SearchGUI so it takes all IDs as they come and doesn't try to perform the cross-references it does?

No, I'm afraid not. These checks are essential to be able to refer to a specific protein sequence in the FASTA file. So the only way around the issue is to reformat the FASTA headers.

> After trying to replace all | with _, I thought SearchCLI would not try to parse the IDs

Try replacing with a single white space instead. That should result in SearchGUI taking the whole header as the accession number. At least this works for the PDB headers you listed above.

**Comment by iquasere** [comment]
After replacing with white space, it works for all IDs. Thank you very much again @hbarsnes @CarlosHorro
