### ISSUE TITLE
Trypsin No P rule does not work with MSGF+

### ISSUE THREAD

**Issue by veitveit** [compomics/searchgui#287]
Not sure whether you already corrected this. 
In version 4.0.12, the Trypsin No P rule option triggers an enzyme ID of 10 which is not allowed in MSGF+. The correct one most likely is their normal Trypsin option as they do not include the no P rule there.

**Comment by hbarsnes** [comment]
Thanks for telling us about this! Seems like MSGF+ for some reason has removed their support for custom enzymes... :(

However, this is not in line with their documentation, see https://msgfplus.github.io/msgfplus/examples/enzymes.txt, where they state "New enzymes will continue the numbering at 10". So most likely it is just a matter of being too strict when validating the input parameters?

I would recommend that you set up an issue in the MSGF+ issue tracker (https://github.com/MSGFPlus/msgfplus/issues)?

As soon as they release a new version which yet again supports custom enzymes we'll update the version included in SearchGUI.

**Comment by hbarsnes** [comment]
Or maybe there is a bug on our side after all. Or in addition to... So let me dig a bit more before you create the MSGF+ issues.

**Comment by hbarsnes** [comment]
Nope, I stick to my initial opinion of this being an MSGF+ issue. Seems to have been an issue for a long time though...

**Comment by hbarsnes** [comment]
I take it back. The key is this line in the MS-GF+ documentation: "Create file params\enzymes.txt (or params/enzymes.txt on Linux) below the working directory to define custom enzymes or override the cleavage residues for built-in enzymes".

And the reason being that since SearchGUI 4.0.9 we allow the users to take control over the search engine temp folders (as required on certain read-only systems). Which works fine for MS-GF+ when it comes to the modifications (as we can point to a specific file with the modification details), but apparently not for the enzymes as there the folder/file cannot be changed.

I will set up an MS-GF+ issue and see if they can do the same for the enzymes as what they already support for the modifications. This should solve the problem.

**Comment by hbarsnes** [comment]
Turned out there was no need for involving the MS-GF+ developers after all, as we can simply change the working directory for the MS-GF+ process instead. With some other minor changes the custom enzymes should now be supported for MS-GF+ again. 

I've just releases SearchGUI v4.0.21 which should solve the problem. If this is not the case, please let me know and I'll reopen the issue.
