### ISSUE TITLE
database - decoy problem 

### ISSUE THREAD

**Issue by tivdnbos** [compomics/searchgui#290]
Hi,

I am using an concatenated database for an X!Tandem search; but slightly modified:
I remove "_REVERSED" and replace the ">"  with ">decoy_" (I do this because I use the result files as input in Percololator, which can only work with such a prefix). 
However, when loading the concatenated database in SearchGUI, it looks like a lot of the decoy proteins are considered as target proteins (e.g. >decoy_sp|ALBU_BOVIN| is considered a target protein in the preview window).

What can I do to resolve this? Note that my decoy tag needs to stand right after the ">" sign.

Best,
Tim

**Comment by hbarsnes** [comment]
Hi Tim,

SearchGUI does support prefix decoy tags, but only as part of the accession number. See for example:

![decoys](https://user-images.githubusercontent.com/13151214/111468781-37d2c900-8726-11eb-9a59-735b8680a0c7.PNG)

And only if you change the FASTA parsing options when adding the decoys in the first place.

Also note that ">decoy_sp|ALBU_BOVIN|" will not be a valid decoy tag as the decoy tag is not part of the accession number. For that to be the case you would have to change this one to ">sp|decoy_ALBU_BOVIN|".

In other words, simply adding "decoy_" to the start of the header will not work as then we have no way of knowing how to parse the header in order to find the accession number. There might be ways around this, but they would require manual editing of the decoy headers. For example, I think that if you change the decoy headers to being only of the type ">decoy_ALBU_BOVIN" then the whole header will probably be used as the accession number and the decoy tag should be picked up. I have not yet tested this though.

If this this not work, I guess we would have to look into changing the decoy parsing code to pick up any headers starting with "decoy" (or more generally the decoy prefix tag given by the user) and designate these as decoys. Should not be too hard. However, we'd also need to update the creation of the decoy headers in the first place as well. I cannot say when I will have the time to look into this though. So feel free to look at the code yourself. :)

Best regards,
Harald

**Comment by tivdnbos** [comment]
Hi Harald, 

thanks for the quick response. My decoy headers now look like ">decoy_sp|decoy_ALBU_BOVIN|", and it seems to work (at least: SearchGUI counts the same number of targets and decoys, so that's a good sign). Since they still start with >decoy, Percolator will still recognize them as decoys.

Best,
Tim

**Comment by hbarsnes** [comment]
Hi Tim,

Aha, that is a nice workaround. I will close the issue then. But feel free to reopen it if you come across more issues down the line.

Best regards,
Harald
