### ISSUE TITLE
Comet stuck after loading mzML spectra

### ISSUE THREAD

**Issue by ttessie2** [compomics/searchgui#297]
I'm having an issue running comet. After converting the thermo .raw file with thermoRawFileParser in searchGUI to an mzML and running a search with comet it stalls after loading the spectra. I don't have this issue if I convert the raw file to a mgf file though. Also, the conversion to an mzML file works fine if I run MSGF+ after.

**Comment by hbarsnes** [comment]
Thanks for telling us about this. I'm assuming there is something unusual with the given mzML file that causes problems for Comet. Does Comet provide any error message or does it simply halt completely?

BTW, I just tested on my side and Comet worked fine for one of the test raw files I had available. Do you have other raw files that you can try to see if the issue is specific to one raw file?

**Comment by ttessie2** [comment]
Sorry for the late reply. But I have it working, there was something wrong the those files. Not sure what, but other files seem to work. Thanks!
