### ISSUE TITLE
Index out of range exception thrown by Andromeda for a MGF file

### ISSUE THREAD

**Issue by animesh** [compomics/searchgui#318]
I am trying to analyze a MGF and facing this error:

![image](https://user-images.githubusercontent.com/21457/151954837-8fe34b5e-e2d3-4788-95be-53f1832debb1.png)

```
Tue Feb 01 11:16:19 CET 2022        Andromeda configuration.


Tue Feb 01 11:16:22 CET 2022        Importing spectrum files.
Tue Feb 01 11:16:22 CET 2022        Importing spectrum file 20200909_MKA_H12C_PeptidesDHB_DDA.mgfcomb.mgf
Tue Feb 01 11:16:22 CET 2022        Importing spectrum files completed (2.0 milliseconds).


Tue Feb 01 11:16:22 CET 2022        Converting spectrum file 20200909_MKA_H12C_PeptidesDHB_DDA.mgfcomb.mgf for Andromeda.
Tue Feb 01 11:16:22 CET 2022        Processing 20200909_MKA_H12C_PeptidesDHB_DDA.mgfcomb.apl with Andromeda.

Start Search.

Unhandled Exception: System.Exception: Exception during execution of external process: 11604
   at BaseLibS.Util.WorkDispatcher.ProcessSingleRunExternal(Int32 taskIndex, Int32 threadIndex)
   at BaseLibS.Util.WorkDispatcher.DoWork(Int32 taskIndex, Int32 threadIndex)
   at BaseLibS.Util.WorkDispatcher.Work(Object threadIndex)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)


Tue Feb 01 11:49:37 CET 2022        Andromeda finished for 20200909_MKA_H12C_PeptidesDHB_DDA.mgfcomb.apl (33 minutes 16.0 seconds).

Tue Feb 01 11:49:37 CET 2022        Zipping output files.

Tue Feb 01 11:49:37 CET 2022        Processing identification files with PeptideShaker.

Tue Feb 01 11:49:55 CET 2022        PeptideShaker processing canceled. Please see the PeptideShaker log file: F:\OneDrive - NTNU\Downloads\PeptideShaker-2.2.4\PeptideShaker-2.2.4\resources\PeptideShaker.log

Tue Feb 01 11:49:55 CET 2022        Searching Canceled!
F:\OneDrive - NTNU\Downloads\PeptideShaker-2.2.4\PeptideShaker-2.2.4\resources\matches\noC5720220201-114940.psdb could not be deleted!
Tue Feb 01 11:50:04 CET 2022        The search or processing did not finish properly!

```

SearchGUI settings are shown in screenshot below:

![image](https://user-images.githubusercontent.com/21457/151945310-b303793d-aa90-4ca5-af48-f9e279b3e7ca.png)

![image](https://user-images.githubusercontent.com/21457/151945385-f1e1e8a2-c9cb-4df8-a35c-c285fc259e42.png)

![image](https://user-images.githubusercontent.com/21457/151945269-1b048b6e-f394-4d5d-b2e1-df5ceab6c662.png)

I must mentioned that a random sample from the same file into another MGF, that works (peptide-shaker screenshot below):
![image](https://user-images.githubusercontent.com/21457/151945458-5c470dbe-be44-4654-91f8-65f2ae8bdb72.png)

Also if i convert the original to mzML, that seems to work as well:
![image](https://user-images.githubusercontent.com/21457/151949747-4041af69-b35a-493b-b0b0-12cb5093144e.png)

So i am guessing this is MGF->APL conversion issue?

**Comment by hbarsnes** [comment]
Hi Animesh,

To be honest, I have a hard time making sense of the Andromeda error messages, but it is indeed odd that the error only occurs for the mgf file and not for the mzML file. This could be related to the mgf to apl conversion, but the mzML input is also converted to apl, so I think it rather means that the two apl-files do not contain the same spectra.

Can you share the mgf and mzML files so that I can have a closer look?

Best regards,
Harald

**Comment by hbarsnes** [comment]
Thanks for sharing the spectrum files! However, I get the same error for both the mgf and mzML files, which makes sense as the resulting apl files are identical (except for the spectrum titles). I think the main problem here may be the spectra themselves. For example, there seem to be no peak picking? There are also several spectra with very few peaks that ought to be filtered out? Finally, there are a lot of singly-charged precursors which are usually not included in mgf files?

On the other hand, some of the other search engines, e.g. Comet, are able to process the file. Any chance you can simply switch to one (or more) of the other search engines instead? As I'm not sure how much further we'll get on the Andromeda issue. Unless you want to spend time trying to narrow the issue down to which single spectrum is causing the issue? If that is indeed what the problem is the first place...

**Comment by animesh** [comment]
Thanks for trying @hbarsnes 👍 Yes, comet/Sequest works on the data, i was just curious why mzML worked but then even that doesn't work for you so i guess it will be impossible for you to debug. I will close the issue.

**Comment by hbarsnes** [comment]
Of course I could not help but dig a bit deeper anyway. ;)

Seems like you are maybe hitting an upper limit regarding the number of peaks in one spectrum that Andromeda can handle. At least Andromeda still fails when using a single spectrum containing 2748 peaks as input. But if I roughly cut the last half to a total of 1264 peaks, the search completes. Not 100% sure if this is the problem, but it at least shows that your spectra are not what I'd call normal? On a related note, the m/z-values are not in ascending order, which is also unusual? So perhaps Andromeda is not entirely to blame for this one? ;)

**Comment by animesh** [comment]
Agreed, too many variables here @hbarsnes , can you give the 
[SGUI.par.txt](https://github.com/compomics/searchgui/files/7995908/SGUI.par.txt) 
 with fasta  https://drive.google.com/file/d/1zqz1optok9PsSkekzEAbF2_fkveB_IrI/view?usp=sharing  a try?

**Comment by hbarsnes** [comment]
The two apl files for the mzML file are (as expected) identical and independent of the search parameters and FASTA file. But while it takes longer to fail with your parameters, it still fails with the same error message as you have above. Same for the mgf file combined with your parameters. (I assume the longer time until it crashes is due to your larger database.)

So not sure how much further we're able to go with this issues? At least it does not seem to be an error with the mgf to apl conversion as far as can tell. Best to just stick to some of the other search engines?
