### ISSUE TITLE
MGF validation error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [compomics/searchgui#32]
```
> What steps will reproduce the problem?
Trying to load a MGF file with missing charge for some precursors.

> What is the expected output? What do you see instead?
An error message "An error occurred while validating the mgf file: could not be 
processed as a valid precursor charge!" pops up.

> What version of the product are you using? On what operating system?
SearchGUI 1.20.8 on Windows 7 64-bit.

> Please provide any additional information below.

Problem MGF file attached, and relevant portion of SearchGUI.log pasted below:

java.lang.NumberFormatException: For input string: ""
    at java.lang.NumberFormatException.forInputString(Unknown Source)
    at java.lang.Integer.parseInt(Unknown Source)
    at java.lang.Integer.<init>(Unknown Source)
    at com.compomics.util.experiment.io.massspectrometry.MgfReader.parseCharges(MgfReader.java:903)
    at com.compomics.util.experiment.io.massspectrometry.MgfReader.getIndexMap(MgfReader.java:245)
    at com.compomics.util.experiment.massspectrometry.SpectrumFactory.addSpectra(SpectrumFactory.java:213)
    at eu.isas.searchgui.gui.SearchGUI.validateMgfFile(SearchGUI.java:3365)
    at eu.isas.searchgui.gui.SearchGUI.access$9700(SearchGUI.java:67)
    at eu.isas.searchgui.gui.SearchGUI$59.run(SearchGUI.java:1543)
java.lang.IllegalArgumentException:  could not be processed as a valid 
precursor charge!
    at com.compomics.util.experiment.io.massspectrometry.MgfReader.parseCharges(MgfReader.java:907)
    at com.compomics.util.experiment.io.massspectrometry.MgfReader.getIndexMap(MgfReader.java:245)
    at com.compomics.util.experiment.massspectrometry.SpectrumFactory.addSpectra(SpectrumFactory.java:213)
    at eu.isas.searchgui.gui.SearchGUI.validateMgfFile(SearchGUI.java:3365)
    at eu.isas.searchgui.gui.SearchGUI.access$9700(SearchGUI.java:67)
    at eu.isas.searchgui.gui.SearchGUI$59.run(SearchGUI.java:1543)



> If the reported issue resulted in the tool crashing, please
> also upload the file called SearchGUI.log (found in the
> SearchGUI-X.Y.Z\resources folder).

```

Original issue reported on code.google.com by `EssArrAi...@gmail.com` on 17 Sep 2014 at 4:44

**Comment by FabrizioDonnarumma** [comment]
I encountered a similar problem today.

I have a PKL (Waters) dataset. I converted it to MGF (MSCONVERT) and I noticed that the CHARGE field was present (and all charges had a + at the end, CHARGE=2.0+)

I had to manually delete all the entries.

**Comment by hbarsnes** [comment]
Maybe I misunderstand your comment, but the charge field is a standard field in mgf files (see http://www.matrixscience.com/help/data_file_help.html) and there should be no reason to remove them (unless they are empty as in the issue reported above). The plus at the end is also perfectly fine. However, the charge itself ought to be an interger, i.e., "CHARGE=2.0+" should be "CHARGE=2+".

How did you convert your pkl file using msconvert btw? Because as far as I can see msconvert does not support pkl files? At least it results in a "don't know how to read" error on my side if I try.

**Comment by FabrizioDonnarumma** [comment]
Hi, 
You are correct, I remembered the correct format after I sent the message.

The issue is the following:
I have PKL files generated with a ProteinLynx Global Server (PLGS) workflow. The raw data come from a DIA experiment. I tried to use the files as it is in the Searchgui, but the programs fails to find the converted mgf file (it searches for the wrong file, since the outpur from MSConvert is named differently from the original files).
Therefore, I converted manually and used the MGF file in the search. And It gave me the error about the charge.
I noticed the ALL the CHARGE field were in the format CHARGE=X.0+
Additionally, some charges were labelled with one or two decimals (such as CHARGE=4.39+).

I solved the problem with REGEX based find and replace.
For the CHARGE=X.Y+ and CHARGE=X.YZ+ cases, I used the following expression respectively
\.\d\+ and \.\d\d\+ 

The search I started is still running, but the file passed the validation.

**Comment by hbarsnes** [comment]
> I tried to use the files as it is in the Searchgui, but the programs fails to find the converted mgf file (it searches for the wrong file, since the outpur from MSConvert is named differently from the original files).

Which version of SearchGUI are you using? If you upgrade to SearchGUI v2.3.5 the name of the mgf file should be the same as the name of the raw file. (As we just detected and fixed the same problem for wiff file conversion.)

**Comment by FabrizioDonnarumma** [comment]
When I tried what I wrote above, I was using 2.3.4
Now I am using  2.3.5 but I did not try to convert directly from searchGUI yet.

**Comment by FabrizioDonnarumma** [comment]
I tried the conversion directly from searchGUI (2.3.5) and it managed to find the files.

The issue about the CHARGE is still present thoush

Mon Jan 11 13:48:14 CST 2016        Processing 12_14_2015_Rat_S2P2.mzML with msconvert.

processing file: E:\Data\Fabrizio\Baylor Project\12_14_2015_Rat_S2P2.mzML
writing output file: E:\Data\Fabrizio\Baylor Project\12_14_2015_Rat_S2P2.mgf


Mon Jan 11 13:50:30 CST 2016        msconvert finished for 12_14_2015_Rat_S2P2.mzML (2 minutes 15 seconds).


Mon Jan 11 13:50:30 CST 2016        Indexing spectrum files.
Mon Jan 11 13:50:30 CST 2016        Error: '2.0+' could not be processed as a valid precursor charge!
Mon Jan 11 13:50:30 CST 2016        An error occurred while running SearchGUI. Please contact the developers.
Mon Jan 11 13:50:30 CST 2016        The search or processing did not finish properly!

Mon Jan 11 13:50:30 CST 2016        Search Canceled!

**Comment by hbarsnes** [comment]
I guess we could always read the charge as a floating value and then convert it to an integer. Which is no problem for '2.0+' for example. But what about '4.39+'? Do we set it to the closest integer? The easiest would be to just keep the integer part, but not sure if that is correct?

But then a charge as a floating value makes no sense in the first place..? And the Mascot mgf file parameter description clearly states that the charge should be an integer. So I'd say that this is an invalid mgf file, but the problem seems to be introduced further upstream, probably in the raw file itself?

**Comment by FabrizioDonnarumma** [comment]
At the moment, I believe that the problem is in the raw->mzXL conversion or in the raw itself.
I will check with WATERS engineers and see if they detect anything on their end.

The issue belongs to about 15% of my spectra.
At the moment, I am keeping the integer. This is clearly wrong, for 4.7 might mean 5 and 4.4 might mean 4. Or they might both mean 4. Or 5.

In addition, I getting a series of errors both with searchGUI and Peptide Shaker.
Mostly, bad calls that close one of the engines during the search or send the java into loop during results import.
I will write something more specific when I get some results.
