### ISSUE TITLE
OMSSA issues

### ISSUE THREAD

**Issue by carolinelennartsson** [compomics/searchgui#330]
There is an issue occurring when running OMSSA. Could you help me fix the issue? 

<img width="549" alt="Screenshot 2022-10-03 at 17 15 24" src="https://user-images.githubusercontent.com/70753896/193623740-7e2f537d-db82-4678-8017-e4545ad50744.png">

<img width="798" alt="Screenshot 2022-10-03 at 17 15 35" src="https://user-images.githubusercontent.com/70753896/193623761-d1e4b780-9868-4d13-a8ee-3353e68abc00.png">

**Comment by hbarsnes** [comment]
I'm afraid that OMSSA is a quite old search engine that is no longer supported by the original developers. There may therefore be newer operating systems that are not able to run OMSSA, for example due to missing libraries. In such cases, I would generally recommend rather using some of the other newer search engines included in SearchGUI. However, if you want to dig deeper into why OMSSA is not running, you can always try to run the above osx command directly from the command line. This should give you more details about why it fails to start.
