### ISSUE TITLE
Does not work with me

### ISSUE THREAD

**Issue by kailaw138** [compomics/searchgui#341]
I conducted a search with a Thermo raw file using SearchGUI 4.1.24

I tried XTandem, OMSSA, Tide etc... it said it was converting the spectrum file to peak list... but even a few hours later, nothing happened. The CPU was ideal.

Then I switched to Comet, it could not read the mzml file generated and the search canceled itself.

see screenshots

![Screenshot 2022-12-15 190002](https://user-images.githubusercontent.com/119678591/207846057-30bfa494-8a
![Screenshot 2022-12-15 190030](https://user-images.githubusercontent.com/119678591/207846100-b6178a9b-b92d-4c13-b3f1-2f97697f7e82.png)
86-4380-a33d-aff905ef0341.png)
![Screenshot 2022-12-15 190717](https://user-images.githubusercontent.com/119678591/207846119-c78e038f-dc0f-45ef-bf06-b9d668962f41.png)

**Comment by hbarsnes** [comment]
The first problem is probably due to using an older Java version. I would recommend updating to a more recent version here: https://adoptium.net/temurin/releases.

The second issue is due to Comet requiring indexed mzml files. If the mzml files was created outside of SearchGUI you will need to redo the conversion and make sure that indexed mzml is used.

The conversions to mzml can also be done inside SearchGUI, but then you will again have to make sure that indexed mzml is selected by clicking the cogwheel at the end of the ThermoRawFileParser line in the main SearchGUI dialog. (Note that indexed mzml will be the default in the next release and then this extra step will no longer be needed.)

**Comment by hbarsnes** [comment]
Issue assumed resolved. It this is not the case, please let us know and we'll reopen the issue.
