### ISSUE TITLE
Hello I am a user using searching gui and peptide shaker.

### ISSUE THREAD

**Issue by kyungsikshi** [compomics/searchgui#342]
I am a user of peptide shaker. 

I want to find peptides after microbial fermentation.

1. I want to find peptides under 8 amino acid sequences. However, even though I change the analysis condition, minimum level of pepties are eight. How can I can peptides with lower length than 8.

2. I saw a massage that saids

Wed Jan 11 15:29:13 KST 2023        6359 of the best scoring peptides were excluded by the import filters:
Wed Jan 11 15:29:13 KST 2023            - 99.6% peptide length less than 8 or greater than 30.

I want to get peptides with out excluding tham. How can I change  the analysis condition to get all 6359 peptides?

**Comment by kyungsikshi** [comment]
For the fist Issue,

Even though I change searching condition of peptide length to 4 to 20, minimum lenghth of the result is 8.

**Comment by hbarsnes** [comment]
There are two sets of settings to consider here: the search settings in SearchGUI and the import filters in PeptideShaker.

In order to get peptides in the size range you want you first have to make sure that the each of the search engines actually search for peptides of the wanted lengths. This has to be changed for each search engine via the advanced search settings available by clicking the cog wheel after each search engine in the main SearchGUI dialog.

Next, you have to change the default peptide size filter for PeptideShaker. This is done via the Identification Settings dialog by clicking the Show Advanced Settings link and then the Import Filters option. See the below screenshot:

![image](https://user-images.githubusercontent.com/13151214/211792129-3936071e-8264-4df0-9376-3f51fff5d640.png)

**Comment by hbarsnes** [comment]
Issue assumed resolved. It this is not the case, please let us know and we'll reopen the issue.
