### ISSUE TITLE
error with mzML file

### ISSUE THREAD

**Issue by danyunghsu** [compomics/searchgui#344]
Hi,
I loaded mgf files of my data in SearchGUI and searched with OMSSA. My searching cancelled in several seconds and shows that there is some problem with one of my spectrum files. The problem occurred when i loaded raw files as well. So, does this mean that there is some problem with my original raw/mgf file?
![屏幕截图 2023-02-25 224301](https://user-images.githubusercontent.com/126338073/221363049-42e0e45a-0e1b-4273-9d07-d7a971fcf991.png)

**Comment by hbarsnes** [comment]
Indeed there seems to be an issue with the spectrum files. Would it be possible for you to share some of these files so that I can have a closer look? What sort of errors do you get when using mgf files by the way?

**Comment by danyunghsu** [comment]
Hi Harald,
I shared the mgf and raw file with an error to your email.
Danyung

**Comment by hbarsnes** [comment]
Hi Danyung,

Thanks for sharing the spectrum files! As far as I can tell there is nothing wrong with the two files you sent me.

In the screenshot above you however seem to use the raw or mzml version of the a498r1 spectrum file as input. What happens if you use the mgf file you sent me as input instead?

Could it be that something went wrong when SearchGUI initially tried to convert the raw file to mzml? Perhaps running out of disk space or something like that? I would suggest deleting the created a498r1.mzml file and then use the raw file as input once again.

Best regards,
Harald

**Comment by danyunghsu** [comment]
Hi Harald,
It seems that the problem took place when SearchGUI initially tried to convert the raw file using ThermoRawFileParser. I deleted the mzML files and used the raw files as input, problem solved. Thanks for helping!
Danyung
