### ISSUE TITLE
omssa: not enough peaks in spectra

### ISSUE THREAD

**Issue by danyunghsu** [compomics/searchgui#345]
Hi all,
I've been searching my raw data files with almost all the search engines in SearchGUI recently. There was no problem with other search engines(including Tide, X!Tandem, MSGF+ and so on) only an error occurred when i opened OMSSA today and received the result that there were not enough peaks in spectra. The search didn't shut down but there was no progress. Attached is the error I receive.
![OMSSAerror](https://user-images.githubusercontent.com/126338073/222743284-d29b4304-6a92-475a-b615-bd47bb08c5b0.png)

**Comment by hbarsnes** [comment]
This just means that OMSSA kicked out some of your spectra as they did not pass its peak count filter. Many of the other search engines have similar filters though, they just do not all tell you how many spectra where filtered out because of it.

Keep in mind that OMSSA is a rather old search engine and in general I would recommend rather using one or more of the new search engines instead, especially if OMSSA is very slow or not working as wanted.

**Comment by danyunghsu** [comment]
Hi Harald,
I'll start the search again. Thanks for solving my problem!
Have a nice day!
Danyung
