### ISSUE TITLE
Different results got from MS Amanda2.0 standalone and SearchGUI.

### ISSUE THREAD

**Issue by JuneCoco** [compomics/searchgui#350]
I would like to identify peptides for immunopeptide experiments and have tried using both MS Amanda2.0 standalone and MS Amanda2.0 in SearchGUI with identical parameters set as same as possible. The input data and database were exactly the same for both tests. 
However, I obtained distinct results from these two. While the standalone version of MS amanda2.0 identified more target peptides, MS amanda2.0 in SearchGUI missed most of them. Additionally, the standalone version took much longer (two to three days) to complete the task compared to MS amanda2.0 in SearchGUI (one to two hours).
I prefer the shorter processing time but the results are not acceptable. What could be causing the differences between the two tests? Thank you!

**Comment by hbarsnes** [comment]
Have you made sure that the advanced MS Amanda parameters are also identical? In SearchGUI you find these by clicking the cogwheel at the end of where you selected MS Amanda in the main SearchGUI dialog. Especially make sure that the peptide length setting is correct.

Next, please check that the filter settings for PeptideShaker are as wanted (assuming you are using it to process the search results?). You'll find these by clicking the "Show Advanced Settings" link in the Identification Settings dialog and opening the Import Filters. Again, the peptide length setting is important.

**Comment by JuneCoco** [comment]
I have adjusted the advanced parameters in MS Amanda and ensured that any SearchGUI parameters that are also available in MS Amanda standalone have been set accordingly. The remaining parameters have been left at their default values. I can provide you with the params file for reference.
https://github.com/JuneCoco/Peptide_identify/blob/main/MSamanda_settings.xml
https://github.com/JuneCoco/Peptide_identify/blob/main/SearchGUI_param.par

I did not use PeptideShaker yet. No filters were applied to the results of both tests. Additional details can be found in the params files.

**Comment by JuneCoco** [comment]
> I have adjusted the advanced parameters in MS Amanda and ensured that any SearchGUI parameters that are also available in MS Amanda standalone have been set accordingly. The remaining parameters have been left at their default values. I can provide you with the params file for reference. https://github.com/JuneCoco/Peptide_identify/blob/main/MSamanda_settings.xml https://github.com/JuneCoco/Peptide_identify/blob/main/SearchGUI_param.par
> 
> I did not use PeptideShaker yet. No filters were applied to the results of both tests. Additional details can be found in the params files.

**Comment by hbarsnes** [comment]
Note that while the MS Amanda search is running (and before it ends), you can find the specific MS Amanda settings file used in the following location: SearchGUI-4.2.9\resources\temp\search_engines\msamanda\settings_SearchGUI.xml.

Using this file instead of the SearchGUI parameters file should make it easier to compare the setting to the standalone version.

Note also that in the file SearchGUI-4.2.9\resources\SearchGUI.log you will find the specific MS Amanda command line being run by SearchGUI. In case there may be differences there as well.

Finally, note that SearchGUI only processes one spectrum file at the time (as the results will later be merged in PeptideShaker), hence make sure that when you are comparing the results you are doing it for the same spectrum file.

**Comment by hbarsnes** [comment]
Issue assumed resolved. If this is not the case, please let us know and we'll reopen the issue.
