### ISSUE TITLE
packaged linux64 myrimatch seg fault

### ISSUE THREAD

**Issue by jflucier** [compomics/searchgui#58]
Hello,

the packaged linux64 Myrimatch software generates a segmentation fault upon execution:

> /home/jflucier/apps/compomics/SearchGUI-2.0.5/resources/MyriMatch/linux/linux_64bit/myrimatch
Segmentation fault (core dumped)

However, when I used my own installation everything is ok:

/home/jflucier/apps/myrimatch-2_2_140/myrimatch -cpus 24 -ProteinDatabase /home/jflucier/apps/tutorial/searchgui/test_decoy.fasta /home/jflucier/apps/tutorial/searchgui/ANTONV_J130605_003.mgf -OutputFormat mzIdentML -workdir /home/jflucier/apps/tutorial/searchgui/out/.SearchGUI_temp -OutputSuffix .myrimatch -DecoyPrefix "" -MinPeptideLength 6 -MaxPeptideLength 30 -MaxResultRank 10 -SpectrumListFilters "" -FragmentMzTolerance "0.1 daltons" -MonoPrecursorMzTolerance "0.006 daltons" -PrecursorMzToleranceRule "mono" -StaticMods "C 57.021464" -DynamicMods "M 0 15.994915 ( 1 42.010565" -MaxDynamicMods 5 -StatusUpdateFrequency 10 -NumChargeStates 5+ -TicCutoffPercentage 0.98 -MinPeptideMass 0.0 -MaxPeptideMass 10000.0 -UseSmartPlusThreeModel true -ComputeXCorr false -NumIntensityClasses 3 -ClassSizeMultiplier 2 -NumBatches 50 -MaxPeakCount 100 -MonoisotopeAdjustmentSet [-1,2] -FragmentationAutoRule false -FragmentationRule "cid" -CleavageRules "Trypsin" -MinTerminiCleavages 2 -MaxMissedCleavages 2
Process #0 (ip32) is starting.
MyriMatch 2.2.140 (2014-4-4)
FreiCore 1.6.230 (2014-4-7)
ProteoWizard MSData 3.0.5941 (2014-3-20)
ProteoWizard Proteome 3.0.4080 (2012-11-7)
Vanderbilt University (c) 2012, D.Tabb/M.Chambers/S.Dasari
Licensed under the Apache License, Version 2.0
....

JF

**Comment by hbarsnes** [comment]
Hi JF,

Thanks for telling us about this. It seems like we're using the same MyriMatch version number though, so I'm not sure why yours would work and not the one included in SearchGUI? Where did you obtain the version you are using? (I cannot seem to access the MyriMatch download page anymore.)

You can always tell SearchGUI to use your own MyriMatch version though: Edit > Search Engines. Let me know if this solves your problem.

Best regards,
Harald

**Comment by jflucier** [comment]
Im running searchgui under centos6 using command line. I got myrimatch last June. I still have the tar.bz2 file used for installation. I can send it to you if you would like since myrimatch website is down. For now, I symlink the linux64 folder in searchgui to my installation folder. I know I could of just used parameter -myrimatch_folder, but I would like to have a fully fonctionnal searchgui folder.

I thank you very much for support.
JF

**Comment by hbarsnes** [comment]
Hi JF,

I don't remember what the MyriMatch .bz2 file contains, but all we need for SearchGUI is the MyriMatch executable, and we cannot really do any installation besides making the executable available in SearchGUI.

I'm not a Linux user myself, but if you think that we could simply replace our MyriMatch executable with your version, and that this would be a valid solution for most Linux users, we could consider replacing the MyriMatch executable with the one you have?

However, if your version only works because you have performed additional installation steps I'm afraid there is not much we can do. But as you write you can always use the -myrimatch_folder option (or the symlink alternative).

Best regards,
Harald
