### ISSUE TITLE
MGF+ fails with Error while indexing:

### ISSUE THREAD

**Issue by wolski** [compomics/searchgui#65]
MGF+ exits with the following error message when run from SearchGUI. See balow the  command line taken from the SearchGUI.log with the error mesage. The error message of MSGF actually suggest to run it with the -tda 0 option.

[-tda 0/1] (0: don't search decoy database (Default), 1: search decoy database).

Not sure about the details but I think that since SearchGUI inserted decoys into the search database
than -tda 0 should be default?

C:\Users\wolski>"C:\Program Files\Java\jre1.8.0_60\bin\java" -Xms128M -Xmx4096M -jar "C:\local\SearchGUI-2.0.11\resources\MS-GF+\MSGFPlus.jar" -s "D:\projects\p
1958\data\datafiles\mgf\120712_CB_Buffy21_W_ReZipTipped_20_Rep_2_msms3.mgf" -d "D:\projects\p1958\data\databases\CNCL_05640_2015_09_concatenated_target_decoy.fa
sta" -o "D:\projects\p1958\output\20151012\.SearchGUI_temp\120712_CB_Buffy21_W_ReZipTipped_20_Rep_2_msms3.msgf.mzid" -t 10.0ppm -tda 1 -mod "C:\local\SearchGUI-
2.0.11\resources\MS-GF+\Mods.txt" -minCharge 2 -maxCharge 4 -inst 3 -thread 5 -m 3 -e 0 -protocol 0 -ntt 2 -minLength 5 -maxLength 15 -n 10 -addFeatures 0 -ti "
-1,2"
MS-GF+ Beta (v10282) (12/19/2014)
Loading database files...
Error while indexing: CNCL_05640_2015_09_concatenated_target_decoy.revCat.fasta (too many redundant proteins)
If the database contains forward and reverse proteins, run MS-GF+ (or BuildSA) again with "-tda 0"

**Comment by mvaudel** [comment]
Dear Witold,

We don't use the option "-tda 1" by default because we try to keep the search engines blind, i.e. unbiased, toward target and decoy sequences. We estimate error rates subsequently for all search engines, and hence try to stay as unbiased as possible. You can change this option from the gui by editing the MS-GF+ specific settings (see 'Search Decoy Database'), or in command line using the 'msgf_decoy' option.

Here it however seems to be a problem with the high degree of similarity between your sequences, and am not sure whether removing the decoys will help. If you are using home made databases it can also be that the algorithm has troubles parsing your header. If you use the format described here (https://github.com/compomics/searchgui/wiki/DatabaseHelp#non-standard-fasta) all search engines in SearchGUI should work. Can you make the database available to me so that I can give it a go on my side?

Hope that helps,

Marc

**Comment by wolski** [comment]
Dear Marc,

I understand you point, to use tda 0 by default. Althoug MSGF --help
 [-tda 0/1] (0: don't search decoy database (Default), 1: search decoy database)

claims to set tda to 0 by default,  to me it seems that this is NOT the case. At least with the version you ship with search GUI.

If I explicitely specify 
-tda 0 
than the MSGF plus runs fine..

if I explicitely set it to 
-tda 1 
It fails with the errors I previously posted.

So not specifying tda apperently is the same as specifiying -tda 1


Regards




What I wanted to suggest is that you explicitely add the -tda 0 option to the command line you generate.

I do not think that there is no problem with the database I do have. It is swissprot human canonical and the decoys were added by searchgui.

**Comment by wolski** [comment]
Again you are correct. For some reason Search Decoy Database in MS-GF+ was set to yes in the gui and there is actually -tda 1 in the command line.  

Not sure why it was set to yes. I can't remember doing it.

**Comment by mvaudel** [comment]
Hi again,

I was able to reproduce the error with -tda 1 on human canonical with
reversed, and confirm that it works file with -tda 0. SearchGUI seems to
behave as intended, and when not specifying tda in command line ms-gf+
works as well so I assume it takes -tda 0 as default in agreement with the
documentation.

So everything seems to work as wanted, and if you confirm we can close the
issue :)

Best regards,

Marc

2015-10-15 10:50 GMT+02:00 Witold Wolski <notifications@github.com>:
