### ISSUE TITLE
Issues with Tide search

### ISSUE THREAD

**Issue by uhaifabioinfo** [compomics/searchgui#94]
Hi,

A Tide search was aborted due to an error. Please see the attached log file.

Thanks!
David.
[250216errorReportSearchGui.txt](https://github.com/compomics/searchgui/files/146265/250216errorReportSearchGui.txt)

**Comment by mvaudel** [comment]
Hi and thank you for reporting this issue.

It seems to be a problem with the Tide index. Can you make sure that the hard drive is not running out of space when Tide is running?

As far as I can see Comet is running fine though, so unless you have interest in having both Tide and Comet, since they are two implementations of the same algorithm you could just consider skipping Tide :)

Best regards,

Marc

**Comment by uhaifabioinfo** [comment]
Hi Marc,

 

Thanks for the quick answer!

 

The drive that contains searchGUI has 86 free Gb and the drive that stores the results has 1.73TB free. Do you think this may be the problem? That it works on two different drives?  

I’m running a comparison analysis of the different algorithms on specific datasets, to check with algorithms have the best complementarity.

I’m using comet too J no big deal though.

 

Thank!

David.

**Comment by mvaudel** [comment]
Hi David,

Having the data on two dives might affect the speed but should not be a
problem for the functioning of the algorithms. Depending on the size of
your database and the search settings, the Tide index can become gigantic,
not sure whether it is the problem here, can we have more information on
the database size and the search parameters, notably number of PTMs?

It is a very good idea to check the performance of the different algorithms
as it can vary from one dataset to the other. However, since both Comet and
Tide are based on Crux you should get very similar ids and the difference
will mainly be the speed. So hopefully Tide not running should not impair
too much your results :)

Best regards,

Marc

2016-02-25 10:58 GMT+01:00 uhaifabioinfo <notifications@github.com>:

**Comment by uhaifabioinfo** [comment]
Hi Marc,

 

The current dataset is ~35000 MS2, searched against Uniprot Human (Canonical + isoform)

The modifications I allowed are NQ amidation, M oxidation, STY phosphorylation, N-term Acetyl. 2 missed cleavages, +2-+5.

 

Thanks!

David.

**Comment by hbarsnes** [comment]
(Issue assumed resolved, if this is not the case please let us know and we'll reopen the issue.)
