### ISSUE TITLE
Connection time out error when trying to download

### ISSUE THREAD

**Issue by LindaSt** [compomics/searchgui#98]
Hi!

I have been trying to donwload the serachgui and the denovogui for linux, but I alway get a connection timed out error in my browser. I have tried it with firefox and chromium and also from two different wifis.

Thanks for your help.
Linda

**Comment by hbarsnes** [comment]
Hi Linda,

I'm afraid that the server where we store all our downloads is not available at the moment due to network issues outside of our control. But it will hopefully be back up on Monday.

Best regards,
Harald

**Comment by 1Moe** [comment]
Hi Harald,
could that also be the reason why searchgui and peptideshaker are slow to start?
cheers
Moe

**Comment by mvaudel** [comment]
Hi Moe,

Yes, the tools are trying to connect to the server and check for new
versions but don't get any answer. We are working on the issue since Friday
but currently all our system for code management, new versions deployment,
and websites are inaccessible. We are really sorry for the inconvenience
but since we cannot anticipate all possible technical problems, a down time
can always happen.

We will make sure that the system comes back up very soon and will do the
necessary improvements to make our system more robust.

Best regards,

Marc

2016-03-20 21:54 GMT+01:00 1Moe <notifications@github.com>:

**Comment by 1Moe** [comment]
Thanks Marc,


don't worry, I'm sure people will understand :)
Really appreciate all the effort you guys are putting in!
cheers
Moe

**Comment by hbarsnes** [comment]
Hi all, 

The download links should now work as before. Please let us know if you still experience any problems.

Best regards,
Harald
